# Generated by Django 3.2.6 on 2021-09-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=64, verbose_name='아이디')),
                ('password', models.CharField(max_length=64, verbose_name='비밀번호')),
                ('username', models.CharField(max_length=64, verbose_name='사용자명')),
                ('gender', models.CharField(choices=[('M', '남성(Man)'), ('W', '여성(Woman)')], max_length=1, verbose_name='성별')),
                ('address', models.CharField(max_length=128, verbose_name='주소')),
                ('like', models.CharField(choices=[('K', '가요(K-POP)'), ('P', '팝(POP)'), ('H', '힙합(HIP-POP)'), ('T', '트롯(TROT)')], max_length=1, verbose_name='좋아하는 장르')),
                ('registered', models.DateTimeField(auto_now_add=True, verbose_name='등록')),
            ],
        ),
    ]
