# Generated by Django 3.2.6 on 2021-09-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(max_length=64, unique=True, verbose_name='아이디'),
        ),
    ]
