# Generated by Django 3.2.6 on 2021-10-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_user_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top100',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('singer', models.CharField(max_length=50, null=True)),
                ('album', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
