# Generated by Django 3.2.6 on 2021-10-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_top100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kpop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('singer', models.CharField(max_length=50, null=True)),
                ('album', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('singer', models.CharField(max_length=50, null=True)),
                ('album', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('singer', models.CharField(max_length=50, null=True)),
                ('album', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('singer', models.CharField(max_length=50, null=True)),
                ('album', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('singer', models.CharField(max_length=50, null=True)),
                ('album', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
