# Generated by Django 3.2.6 on 2021-10-02 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_live_chart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='live_chart',
            name='album',
        ),
    ]
