# Generated by Django 3.2.6 on 2021-10-02 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_remove_live_chart_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kpop',
            old_name='album',
            new_name='k_album',
        ),
        migrations.RenameField(
            model_name='kpop',
            old_name='name',
            new_name='k_name',
        ),
        migrations.RenameField(
            model_name='kpop',
            old_name='singer',
            new_name='k_singer',
        ),
    ]
