# Generated by Django 3.2.6 on 2021-10-02 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20211002_1954'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kpop',
            new_name='Ballad',
        ),
        migrations.RenameModel(
            old_name='Ost',
            new_name='Hip',
        ),
    ]
