# Generated by Django 3.2.6 on 2021-10-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_auto_20211002_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('singer', models.CharField(max_length=50, null=True)),
                ('album', models.CharField(max_length=50, null=True)),
                ('date', models.CharField(max_length=50, null=True)),
                ('kind', models.CharField(max_length=50, null=True)),
                ('many', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='New_Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('singer', models.CharField(max_length=50, null=True)),
                ('album', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
