# Generated by Django 3.2.6 on 2021-10-04 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_mylist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mylist',
            name='active',
        ),
    ]
